"""
DAY 2 · SESSION 3 — MCP + Agents (Advanced): Enterprise Pipeline Audit
=======================================================================
Demonstrates the Copilot Agent + MCP pattern:
  Agent calls MCP tool → analyses → writes findings → creates report

▶ DEMO PROMPT (Copilot Agent mode, MCP active):
───────────────────────────────────────────────────────────────────
Audit our ADF pipelines for:
1. Missing retry policies
2. Pipelines that haven't run in 30+ days
3. Last-run failures
Generate a markdown report saved as audit_report.md
───────────────────────────────────────────────────────────────────
The Agent calls the `audit_pipelines` MCP tool, gets JSON back,
then generates and saves this report file.

Run locally to see the agent output:
    python day2/session3_mcp_agents/demo.py
"""

import json
from datetime import datetime, timedelta
from pathlib import Path


# ── Simulated MCP tool response (matches mcp-server/index.js audit_pipelines) ─
MOCK_MCP_RESPONSE = {
    "total_pipelines": 4,
    "issues_found": 3,
    "issues": [
        {"pipeline": "pl_events_raw_ingest", "issue": "Missing retry policy"},
        {"pipeline": "pl_events_raw_ingest", "issue": "Stale: last run 2024-04-10"},
        {"pipeline": "pl_monthly_rollup",    "issue": "Last run failed"},
    ],
}

PIPELINE_DETAILS = [
    {"name": "pl_sales_blob_to_sql",    "activities": 3, "last_run": "2024-05-20", "status": "Succeeded", "has_retry": True,  "has_alert": True},
    {"name": "pl_customer_dim_refresh", "activities": 2, "last_run": "2024-05-21", "status": "Succeeded", "has_retry": True,  "has_alert": False},
    {"name": "pl_events_raw_ingest",    "activities": 4, "last_run": "2024-04-10", "status": "Succeeded", "has_retry": False, "has_alert": False},
    {"name": "pl_monthly_rollup",       "activities": 5, "last_run": "2024-05-22", "status": "Failed",    "has_retry": True,  "has_alert": True},
]


def generate_audit_report(pipelines: list, issues: list) -> str:
    """Agent generates this markdown report after calling the audit_pipelines MCP tool."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    healthy = sum(1 for p in pipelines if p["status"] == "Succeeded" and p["has_retry"])

    issue_table = "\n".join(
        f"| `{i['pipeline']}` | {i['issue']} | 🔴 Action Required |"
        for i in issues
    )

    pipeline_table = "\n".join(
        f"| `{p['name']}` | {p['last_run']} | {'✅' if p['status'] == 'Succeeded' else '❌'} {p['status']} | "
        f"{'✅' if p['has_retry'] else '❌'} | {'✅' if p['has_alert'] else '❌'} |"
        for p in pipelines
    )

    return f"""# ADF Pipeline Audit Report
*Generated by Copilot Agent + MCP on {now}*

## Executive Summary

| Metric | Value |
|---|---|
| Total Pipelines Audited | {len(pipelines)} |
| Issues Found | {len(issues)} |
| Healthy Pipelines | {healthy} |
| Pipelines Needing Action | {len(set(i['pipeline'] for i in issues))} |

---

## Issues Found

| Pipeline | Issue | Status |
|---|---|---|
{issue_table}

---

## Full Pipeline Status

| Pipeline | Last Run | Status | Retry Policy | Alert |
|---|---|---|---|---|
{pipeline_table}

---

## Recommended Actions

{chr(10).join(f"{j+1}. **`{i['pipeline']}`** — {i['issue']}" for j, i in enumerate(issues))}

### Remediation Template

```json
{{
  "policy": {{
    "retry": 3,
    "retryIntervalInSeconds": 30,
    "timeout": "01:00:00"
  }}
}}
```

Add this `policy` block to the pipeline activity JSON for any pipeline missing retry logic.

---
*Report generated by Copilot Agent using the `audit_pipelines` MCP tool.*
"""


if __name__ == "__main__":
    print("=" * 65)
    print("DAY 2 · SESSION 3 — MCP + Agents: Pipeline Audit")
    print("=" * 65)

    print("\n[1] Agent calls MCP tool: audit_pipelines")
    print("    MCP Response:")
    print(json.dumps(MOCK_MCP_RESPONSE, indent=4))

    print("\n[2] Agent analyses results & generates report...")
    report = generate_audit_report(PIPELINE_DETAILS, MOCK_MCP_RESPONSE["issues"])

    out = Path("day2/session3_mcp_agents/audit_report.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report)
    print(f"\n[3] Report saved → {out}")
    print("\n--- REPORT PREVIEW ---")
    print("\n".join(report.splitlines()[:30]))
    print("...")
    print("\n" + "=" * 65)
    print("Open day2/session3_mcp_agents/audit_report.md to see the full report")
    print("=" * 65)
